apiVersion: apps/v1
kind: Deployment
metadata:
  name: client_deployment
spec:
  selector:
    matchLabels:
      app: client_app
  template:
    metadata:
      labels:
        app: client_app
    spec:
      containers:
      - name: container_client
        image: ./client
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: client_app
spec:
  selector:
    app: client_app
  ports:
  - port: 3000
    targetPort: 3000


