apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: YoloDB
spec:
  selector:
    matchLabels:
      app: YoloDB
  serviceName: dB_Service
  replicas: 1
  template:
    metadata:
      labels:
        app: YoloDB
    spec:
      containers:
      - name: YoloDB
        image: mongo
        ports:
        - containerPort: 27017
          name: mongodb://db/yolomy
        volumeMounts:
        - name: DB_mongo_mnt
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: IP_metadata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi