apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-sideapp
spec:
  selector:
    matchLabels:
      app: server-sideapp
  template:
    metadata:
      labels:
        app: server-sideapp
    spec:
      containers:
      - name: server-sideapp
        image: ./backend
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "300Mi"
            cpu: "300Mi"
          requests:
            memory: "200Mi"
            cpu: "100Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: server-sideapp
spec:
  selector:
    app: server-sideapp
  ports:
  - port: 5000
    targetPort: 5000
