apiVersion: v1
kind: PersistentVolume
metadata:
  name: Redundancy_Vol
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp
    server: 172.17.0.2

---

apiVersion: v1
kind: Redundancy_Vol_Claim
metadata:
  name: mypvc
spec:
  resources:
    requests:
      storage: 850Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

